bg/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'catalog'
urlpatterns = [
    #path('', views.index, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^beers/$', views.BeerListView.as_view(), name='beers'),
    url(r'^beer/(?P<pk>\d+)$', views.BeerDetailView.as_view(), name='beer-detail'),
    url(r'^producers/$', views.ProducerListView.as_view(), name='producers'),
    url(r'^producer/(?P<pk>\d+)$', views.ProducerDetailView.as_view(), name='producer-detail'),
    path('accounts/registration/', views.registration, name = 'registration'),
]

catalog/models.py
from django.db import models
from django.urls import reverse


class Style(models.Model):
    style = models.CharField(max_length=200,
                             help_text="Enter a style of beer (Pale Lager and Pilsner, Dark Lager, German Bock, Brown Ale, Pale Ale, India Pale Ale, Porter, Stout, Belgian-Style Ale, Wheat Beer, Wild & Sour Ale, Specialty Beer)")

    def __str__(self):
        return self.style


class Category(models.Model):
    category = models.CharField(max_length=200, help_text="Enter a category of beer (...)")

    def __str__(self):
        return self.category


class Beer(models.Model):
    name = models.CharField(max_length=200)
    style = models.ManyToManyField(Style, help_text="Select a style of beer")
    category = models.ManyToManyField(Category, help_text="Select a category of beer")
    volume = models.FloatField(max_length=100)
    producer = models.ForeignKey('Producer', on_delete=models.SET_NULL, null=True)
    photo_path = models.TextField(max_length=1000, null=True)
    fact = models.TextField(max_length=1000, null=True)
    score = models.FloatField(max_length=5.0, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:beer-detail', args=[str(self.id)])


class Producer(models.Model):
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    brewer = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('catalog:producer-detail', args=[str(self.id)])

    def __str__(self):
        return '%s, %s' % (self.country, self.city)

catalog/views.py
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from django.contrib import auth
from .models import Beer, Producer, Style, Category
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_beers = Beer.objects.all().count()
    num_producers = Producer.objects.count()  # Метод 'all()' применен по умолчанию.

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={'num_beers': num_beers, 'num_producers': num_producers},
    )

@csrf_protect
def registration(request):
    args = {}
    args['form'] = UserCreationForm()
    if request.POST:
        newuser_form = UserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(username=newuser_form.cleaned_data['username'], password=newuser_form.cleaned_data['password2'])
            auth.login(request,newuser)
            return HttpResponseRedirect('/')
        else:
            args['form'] = newuser_form
    return render(request,'registration/registration.html',args)


class BeerListView(LoginRequiredMixin, generic.ListView):
    model = Beer
    paginate_by = 10


class BeerDetailView(generic.DetailView):
    model = Beer


class ProducerListView(LoginRequiredMixin, generic.ListView):
        model = Producer
        paginate_by = 10


class ProducerDetailView(generic.DetailView):
        model = Producer

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Beer Geek</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'catalog:index' %}">Home</a></li>
          <li><a href="{% url 'catalog:beers' %}">All beers</a></li>
          <li><a href="{% url 'catalog:producers' %}">All producers</a></li>
      {% if user.is_authenticated %}
        <li>User: {{ user.get_username }}</li>
        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
      {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
      {% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}

      {% endblock %}

      {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/beer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ beer.name }}</h1>

  <p><strong>Producer:</strong> <a href="">{{ beer.producer }}</a></p>
  <p><strong>Category:</strong> {% for category in beer.category.all %} {{ category }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  <p><strong>Style:</strong> {% for style in beer.style.all %} {{ style }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  <p><strong>Volume:</strong> {{ beer.volume }}</p>
  <p><strong>Fact:</strong> {{ beer.fact }}</p>

  <div style="margin-left:20px;margin-top:20px">
    Place for comments
  </div>
{% endblock %}

catalog/templates/catalog/beer_list.html
{% extends "base_generic.html" %}


{% block content %}
    <h1>Beer List</h1>

    {% if beer_list %}
    <ul>

      {% for beer in beer_list %}
      <li>
        <a href="{{ beer.get_absolute_url }}">{{ beer.name }}</a> ({{beer.producer}}, Category - {% for category in beer.category.all %} {{ category }}{% if not forloop.last %}, {% endif %}{% endfor %})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no beers in the BeerGeek.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/producer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Country: {{ producer.country }}</h1>

  <p><strong>City:</strong> <a href="">{{ producer.city }}</a></p>
  <p><strong>Brewer:</strong> <a href="">{{ producer.brewer }}</a></p>


  <div style="margin-left:20px;margin-top:20px">
    Place for comments
  </div>
{% endblock %}

catalog/templates/catalog/producer_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Producer List</h1>

    {% if producer_list %}
    <ul>

      {% for producer in producer_list %}
      <li>
        <a href="{{ producer.get_absolute_url }}">{{ producer.country }}</a> ({{producer.city}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no producers.</p>
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Beer Geek Home</h1>

  <p>Welcome to <em>Beer Geek</em>, a super puper place about PIVO.</p>

<h2>Dynamic content</h2>

  <p>The Beer Geek has the following record counts:</p>
  <ul>
    <li><strong>Beers:</strong> {{ num_beers }}</li>
    <li><strong>Producers:</strong> {{ num_producers }}</li>
  </ul>

{% endblock %}